### ISSUE TITLE
Application crashes on MacOS.

### ISSUE THREAD

**Issue by satoshi7190** [sparqlunicorn/sparqlunicornGoesGIS#35]
Hello, I have a problem with the MacOS. I tried this plugin on MacOS and the application crashed the moment I queried it.
I confirm that the problem occurs with "QGIS Version 3.26.3" and "QGIS Version 3.22.11 LTR".

## About MacOS
MacBook Pro (13-inch, M1, 2020)
Memory : 16GB

**Comment by situx** [comment]
Thanks for your bug report. Could you elaborate a bit more on the circumstances of your crash?
Did you enter a query yourself?
To which SPARQL endpoint was there query issued?
Did QGIS issue an error message or did it quit completely?

**Comment by satoshi7190** [comment]
The original query of the plugin crashes; QGIS crashes without error message. But it works fine with the "Roman Open Data" and "Research Squirrel Engineers Triplestore" endpoints.

**Comment by situx** [comment]
Thanks, I reproduced your error. The reason was that the SPARQL endpoint AtlantGIS was offline and is now operating again. The fact that you did not see an error message is something we are working on for a new release - error management.
In any case it should work again now and should not have been a plugin issue.
